theme = "tokyonight_storm"

[editor]
true-color = true
line-number = "relative"
shell = ["zsh","-c"]

[keys.normal]
esc = ["collapse_selection","keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.lsp]
display-messages = true
#display-inlay-hints = true

[editor.soft-wrap]
enable = true
