# Generic Linux tmux config. Installed under ~/.config/tmux.

set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.config/tmux/plugins/"

bind r source-file ~/.config/tmux/tmux.conf
bind -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "xclip -selection clipboard"
