# macOS-specific tmux config. Installed under ~/.tmux.

set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.tmux/plugins/"

bind r source-file ~/.tmux/tmux.conf
bind -Tcopy-mode-vi 'y' send -X copy-pipe-and-cancel "pbcopy"
